//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JCModel
{
    [Serializable]
    [Table("EngineLib")]
    public partial class EngineLib
    {
        private static readonly NLog.Logger Nlogger = NLog.LogManager.GetLogger("Modifer");
        private string _name;
        private decimal? _wheelSize;
        private byte? _axleNum;
        private string _id;

        public EngineLib()
        {
            id = "";
        }

        [Key]
        [DisplayName(@"序列号")]
        public string id
        {
            get { return _id; }
            set
            {
                Nlogger.Trace("编辑表EngineLib的id字段，初始为：" + _id + ",修改后为：" + value);
                _id = value;
            }
        }

        [DisplayName(@"名称")]
        public string name
        {
            get { return _name; }
            set
            {

                Nlogger.Trace("编辑表EngineLib的name字段，初始为：" + _name + ",修改后为：" + value);
                _name = value;
            }
        }

        [Browsable(false)]
        public string fullName { get; set; }
        [Browsable(false)]
        public string factoryId { get; set; }
        [Browsable(false)]
        public Nullable<byte> typeId { get; set; }

        [DisplayName(@"轮径")]
        public Nullable<decimal> wheelSize
        {
            get { return _wheelSize; }
            set
            {
                Nlogger.Trace("编辑表EngineLib的wheelSize字段，初始为：" + _wheelSize + ",修改后为：" + value);
                _wheelSize = value;
            }
        }

        [Browsable(false)]
        public Nullable<decimal> wheelSizeB { get; set; }

        [DisplayName(@"轴数")]
        public Nullable<byte> axleNum
        {
            get { return _axleNum; }
            set
            {
                Nlogger.Trace("编辑表EngineLib的axleNum字段，初始为：" + _axleNum + ",修改后为：" + value);
                _axleNum = value;
            }
        }
    }
}
