//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JCModel
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    [Table("WheelPos")]
    public partial class WheelPos
    {
        private static readonly NLog.Logger Nlogger = NLog.LogManager.GetLogger("Modifer");
        private byte _posNo;
        private string _value;

        [Key]
        [Column(Order = 0)]
        [ReadOnly(true), DisplayName(@"车型")]
        public string trainType { get; set; }

        [Key]
        [Column(Order = 1)]
        [DisplayName(@"轮位")]
        public byte posNo
        {
            get { return _posNo; }
            set
            {
                Nlogger.Trace("编辑表WheelPos的posNo字段，初始为：" + posNo + ",修改后为：" + value);
                _posNo = value;
            }
        }

        [DisplayName(@"描述")]
        public string value
        {
            get { return _value; }
            set
            {
                Nlogger.Trace("编辑表WheelPos的value字段，初始为：" + this.value + ",修改后为：" + value);
                _value = value;
            }
        }
    }
}
